name: ðŸž Bug report
description: "Report a bug or something that is otherwise not working as expected."
labels: ["bug"]

body:      
  - type: checkboxes
    id: diagnostics
    attributes:
      label: Diagnostic Checklist
      description: "Use the checklist below to verify you have ruled-out other potential causes. It can save time if you have already tried basic troubleshooting."
      options:
        - label: "Home Connect app can control the appliance with Wi-Fi disabled."
        - label: "Home Connect app appliance Settings, Network section, shows three green lines."
        - label: "Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and found none."
        - label: "Checked Home Connect API documentation for [errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors)."
        - label: "[Home Connect Server Status (unofficial)](https://homeconnect.thouky.co.uk) shows servers up and no recent errors."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "[![Home Connect Server Status](https://homeconnect.thouky.co.uk/api/images/readme-status.svg)](https://homeconnect.thouky.co.uk)"

  - type: textarea
    id: description
    attributes:
      label: Description of Issue
      description: "Provide a clear and concise description of the bug."
      placeholder: "Describe the bug..."
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: "What did you expect to happen?"
      placeholder: "Describe the expected outcome..."
    validations:
      required: true
    
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: "Provide a step-by-step description of how to reproduce the issue."
      placeholder: |
        Steps to reproduce:
        1. ...
        2. ...
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Plugin Version
      description: "State the plugin version exhibiting the bug. If not using the latest version, please update before reporting."
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Describe the software environment being used to run this plugin. Include:
        - Operating System type and version (output of `lsb_release -d` on Linux)
        - Node.js version (output of `node -v`)
        - Homebridge version (output of `npm -g ls homebridge`)
      placeholder: |
        - OS: e.g. Ubuntu 24.04.1 LTS or macOS Ventura 13.5
        - Node: e.g. v22.15.0
        - Homebridge: e.g. 1.8.5
    validations:
      required: true
  
  - type: input
    id: appliance
    attributes:
      label: Home Connect Appliance(s)
      description: "Provide the appliance manufacturer, type, and model number (if applicable). These details can be found in the Apple Home app or the Homebridge log file."
      placeholder: "e.g. Siemens Oven HB678GBS6B/50"
    validations:
      required: false
      
  - type: input
    id: homekitapp
    attributes:
      label: HomeKit App(s)
      description: "Provide details about the HomeKit app involved (if applicable)."
      placeholder: "e.g. Apple Home, Elgato Eve, Home+ 4, Hesperus, etc."
    validations:
      required: false
      
  - type: textarea
    id: log
    attributes:
      label: Log File
      description: |
        Provide relevant Homebridge logs, either pasted below or attached as a text file. Do NOT use a screenshot. Replace sensitive information (access tokens, etc) with `REDACTED`. Logs are most useful when they are complete; include the full output around the error message and do not omit any lines.

        Enable and capture appropriate extra debug:
        
        - **For Homebridge Debug Logging** (enable for most issues):
          - Launch Homebridge using `homebridge -D` to start in debug mode.
            - In Homebridge UI: *Settings* > *UI Advanced Settings* > *Log Settings* > *Enable/disable debug level logging*.
          - Or, in your `config.json`, add `"debug": ["Log Debug as Info"]` to log debug information as part of regular output.
            - In Homebridge UI: *Plugins* > *HomeConnect Plugin Config* > *General Settings* > *Debug Options* > *Log Debug as Info*.
          
        - **For Home Connect API Logging**:
          - In your `config.json`, add `"debug": ["Log API Bodies"]` to capture the raw API request and response bodies.
            - In Homebridge UI: *Plugins* > *HomeConnect Plugin Config* > *General Settings* > *Debug Options* > *Log API Bodies*.
          
        - **For HomeKit Accessory Protocol (HAP) Logging**:
          - Launch Homebridge using `DEBUG=HAP-NodeJS:* homebridge -D` to enable HAP-specific logging.
        
        The additional debug information in the logs will provide more context for resolving your issue.
      placeholder: |
        Paste the logs...

        With general debug:
          homebridge -D > debug.log

        With Home Connect API logging:
          { "platforms": [{ "platform": "HomeConnect", "debug": ["Log API Bodies"] }] }

        With HAP (HomeKit) logging:
          DEBUG=HAP-NodeJS:* homebridge -D > debug.log
      render: shell
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: "Provide your `config.json` (if relevant). This is optional but highly recommended. Replace sensitive information (Client ID, passwords, tokens, etc) with `REDACTED`."
      placeholder: "Paste configuration..."
      render: json
    validations:
      required: false
   
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: "Provide any additional information that might assist with resolving your bug report. This could include links to product web pages, user manuals, screenshots, videos, or anything else relevant."
      placeholder: "Any other relevant information..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Important Notes:**
        - Ensure all required fields are filled.
        - Debug logs (captured using `homebridge -D`) are crucial for resolving most issues.
        - Ensure sensitive information like tokens or passwords are `REDACTED` before sharing.
        - If you are not using the most recent plugin version, update before submitting.