name: ðŸž Bug report
description: "Report a bug or something that is otherwise not working as expected."
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description of Issue
      description: "Provide a clear and concise description of the bug."
      placeholder: "Describe the bug..."
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: "What did you expect to happen?"
      placeholder: "Describe the expected outcome..."
    validations:
      required: true
    
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: "Provide a step-by-step description of how to reproduce the issue."
      placeholder: |
        Steps to reproduce:
        1. ...
        2. ...
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Plugin Version
      description: "State the plugin version exhibiting the bug. If not using the latest version, please update before reporting."
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Describe the software environment being used to run this plugin. Include:
        - Operating System type and version (output of `lsb_release -d` on Linux)
        - Node.js version (output of `node -v`)
        - Homebridge version (output of `npm -g ls homebridge`)
      placeholder: |
        - OS: e.g. Ubuntu 24.04.1 LTS or macOS Ventura 13.5
        - Node: e.g. v18.20.4
        - Homebridge: e.g. 1.8.5
    validations:
      required: true
  
  - type: input
    id: appliance
    attributes:
      label: Home Connect Appliance(s)
      description: "Provide the appliance manufacturer, type, and model number (if applicable). These details can be found in the Apple Home app or the Homebridge log file."
      placeholder: "e.g. Siemens Oven HB678GBS6B/50"
    validations:
      required: false
      
  - type: input
    id: homekitapp
    attributes:
      label: HomeKit App(s)
      description: "Provide details about the HomeKit app involved (if applicable)."
      placeholder: "e.g. Apple Home, Elgato Eve, Home+ 4, Hesperus, etc."
    validations:
      required: false
      
  - type: checkboxes
    id: diagnostics
    attributes:
      label: Diagnostic Checks
      description: "Indicate steps you have taken to rule out other causes."
      options:
        - label: "Home Connect app can control the appliance with Wi-Fi disabled."
        - label: "Home Connect app appliance Settings, Network section, shows three green lines."
        - label: "[Home Connect Server Status (unofficial)](https://homeconnect.thouky.co.uk) shows servers up and no recent errors."
        - label: "Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and found none."
        - label: "Checked [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation."
    validations:
      required: false
      
  - type: textarea
    id: log
    attributes:
      label: Log File
      description: "Provide relevant logs, captured with Homebridge in debug mode (`-D`). Attach longer logs as a text file. Ensure logs are complete and legible. Do NOT use a screenshot. Replace sensitive information like access tokens with `REDACTED`."
      placeholder: "Paste logs captured using: homebridge -D > debug.log"
      render: shell
    validations:
      required: true
   
  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: "Provide your `config.json` (if relevant). Replace sensitive information (Client ID, passwords, tokens, etc) with `REDACTED`. This is optional but highly recommended."
      placeholder: "Paste configuration..."
      render: json
    validations:
      required: false
   
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: "Provide any additional information that might assist with resolving your bug report. This could include links to product web pages, user manuals, screenshots, or anything else relevant."
      placeholder: "Any other relevant information..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Important Notes:**
        - Ensure all required fields are filled.
        - Debug logs (`-D` mode) are crucial for resolving most issues.
        - Remove sensitive information (e.g., passwords or tokens) from logs.
        - If you are not using the most recent plugin version, update before submitting.