name: 🚫 [AUTOMATED] Internal API report; not for user issues
description: "⚠️ Not for manual use. This template is reserved for automated API diagnostics. Submissions created manually will be closed without investigation."
title: HomeConnect API unexpected values or mismatched types
labels: ["api keys/values"]

body:
  - type: input
    id: version
    attributes:
      label: Plugin Version
      description: "Version number of this plugin that warned about the keys/values. This should be filled automatically. If this is not the most recent release, please update to the latest version before filing the report."
    validations:
      required: true
  
  - type: input
    id: appliance
    attributes:
      label: Home Connect Appliance(s)
      description: "Manufacturer, type, and model number of the associated appliance(s). This should be filled automatically."
      placeholder: "e.g. Siemens Oven HB678GBS6B/50"
    validations:
      required: true
      
  - type: textarea
    id: log
    attributes:
      label: Log File
      description: "Copy/paste all log entries relevant to the reported issue, starting and ending with the horizontal rule markers. Ensure logs are complete and legible. Do NOT use a screenshot. Replace sensitive information like access tokens with `REDACTED`."
      placeholder: |
        Paste logging output here, starting and ending with:
        =============================================================================================
      render: shell
    validations:
      required: true
   
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: "Provide any additional information that might assist with understanding the reported keys/values. This could include links to product web pages, user manuals, screenshots, or anything else relevant."
      placeholder: "Any other relevant information..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Important Notes:**
        - Do NOT use this issue template for general issues.
        - Ensure all required fields are filled.
        - Remove sensitive information (e.g., access tokens) from logs.
        - If you are not using the most recent plugin version, update before submitting.